accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('profile', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
    path('profile/change_password', views.change_password, name='change_password'),
    path('add-location', views.add_location, name='add_location'),

    path('list/customer', views.list_customer, name='list_customer'),
    path('customer/add', views.add_customer, name='add_customer'),
    path('customer/remove/<int:user_id>', views.remove_customer, name='remove_customer'),
    path('customer/change-status/<int:user_id>',views.change_status_customer,name="change_status_customer"),


    path('list/collection-agent', views.list_agent, name='list_agent'),
    path('collection-agent/add', views.add_agent, name='add_agent'),
    path('collection-agent/remove/<int:user_id>', views.remove_agent, name='remove_agent'),
    path('collection-agent/change-status/<int:user_id>',views.change_status_agent,name="change_status_agent"),

    path('list/municipalities', views.list_municipalities, name='list_municipalities'),
    path('add/municipality', views.add_municipalities, name='add_municipalities'),
    path('remove/municipality<int:user_id>', views.remove_municipalities, name='remove_municipalities'),
    path('change-status/municipality/<int:user_id>',views.change_status_municipalities,name="change_status_municipalities"),

    path('list/recyclers', views.list_recyclers, name='list_recyclers'),
    path('recyclers/add', views.add_recyclers, name='add_recycler'),
    path('recyclers/remove/<int:user_id>', views.remove_recycler, name='remove_recycler'),
    path('recyclers/change-status/<int:user_id>',views.change_status_recycler,name="change_status_recycler"),


]

help/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('help', views.help, name='help'),
]

smartrash/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin-django/', admin.site.urls),
    path('', include('help.urls')),
    path('', include('book_recycler.urls')),
    path('', include('booking.urls')),
    path('', include('smartbin.urls')),
    path('', include('query.urls')),
    path('', include('wallet.urls')),
    path('', include('access.urls')),
    path('', include('accounts.urls')),
    path('', include('home.urls')),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    CUSTOMER = "CU"
    COLLECTION_AGENT = "CA"
    MUNICIPALITY = "MU"
    ADMIN = "AD"
    RECYCLER="RE"

    ROLES_CHOICES = [
        (CUSTOMER, "Customer"),
        (COLLECTION_AGENT, "Collection Agent"),
        (MUNICIPALITY, "Municipality"),
        (ADMIN, "Admin"),
        (RECYCLER, "Recycler"),
    ]

    phone = models.CharField(max_length=15)
    housename = models.CharField(max_length=30)
    place = models.CharField(max_length=30)
    municipality = models.ForeignKey(
        'self', on_delete=models.CASCADE, null=True)
    postcode = models.CharField(max_length=6)
    state = models.CharField(max_length=20)
    country = models.CharField(max_length=20)
    profile_image = models.ImageField(upload_to='profile_image')
    role = models.CharField(
        max_length=2, choices=ROLES_CHOICES, null=False, default=ADMIN)


    @property
    def profile_image_url(self):
        try:
            url=self.profile_image.url
        except ValueError:
            url=""
        return url

    @property
    def role_name(self):
        for role_code, role_name in self.ROLES_CHOICES:
            if role_code == self.role:
                return role_name
        return ""


class CollectionAgent(models.Model):
    aadhaar_number = models.CharField(max_length=12)
    license_number = models.CharField(max_length=16)
    aadhaar_image = models.ImageField(upload_to='aadhaar_image')
    license_image = models.ImageField(upload_to='license_image')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    @property
    def aadhaar_image_url(self):
        try:
            url=self.aadhaar_image.url
        except ValueError:
            url=""
        return url

    @property
    def license_image_url(self):
        try:
            url=self.license_image.url
        except ValueError:
            url=""
        return url

class UserLocation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    timestamp = models.DateTimeField(auto_now_add=True)

accounts/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.decorators import login_required
# from access.views import recycler
from accounts.models import CollectionAgent, User, UserLocation
from home.models import RecyclerAmount, WasteAmount
from smartbin.models import SmartBin
from django.contrib import messages
from wallet.models import Wallet
from django.views.decorators.csrf import csrf_exempt



# Create your views here.

@login_required
def profile(request):
    if not (request.user.role == User.CUSTOMER or request.user.role == User.COLLECTION_AGENT or request.user.role == User.MUNICIPALITY or request.user.role == User.RECYCLER):
        return HttpResponse('Unauthorized', status=401)
    if request.method == 'GET':
        municipalities = User.objects.filter(role=User.MUNICIPALITY)
        if request.user.role == User.CUSTOMER or request.user.role == User.RECYCLER:
            context = {'title': 'Profile',
                       'municipalities': municipalities}
        elif request.user.role == User.COLLECTION_AGENT:
            collection_agent = CollectionAgent.objects.get(
                user_id=request.user.id)
            context = {'title': 'Profile', 'municipalities': municipalities,
                       'collection_agent': collection_agent}
        elif request.user.role == User.MUNICIPALITY:
            context = {'title': 'Profile'}
        return render(request, 'profile.html', context)


@login_required
@csrf_exempt
def profile_edit(request):
    if not (request.user.role == User.CUSTOMER or request.user.role == User.COLLECTION_AGENT or request.user.role == User.MUNICIPALITY):
        return HttpResponse('Unauthorized', status=401)
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        if request.user.role == User.COLLECTION_AGENT or request.user.role == User.CUSTOMER:
            last_name = request.POST.get('last_name')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        if request.user.role == User.COLLECTION_AGENT or request.user.role == User.CUSTOMER:
            house_name = request.POST.get('house_name')
            place = request.POST.get('place')
            municipality_id = request.POST.get('municipality')
            profile_image = request.FILES.get('profile_image')
        postcode = request.POST.get('postcode')
        state = request.POST.get('state')
        country = request.POST.get('country')
        if request.user.role == User.COLLECTION_AGENT:
            aadhaar_number = request.POST.get('aadhaar')
            aadhaar_image = request.FILES.get('aadhaar_pic')
            license_number = request.POST.get('license')
            license_image = request.FILES.get('license_pic')
        user = User.objects.get(id=request.user.id)
        user.first_name = first_name
        if request.user.role == User.COLLECTION_AGENT or request.user.role == User.CUSTOMER:
            user.last_name = last_name
        user.phone = phone
        user.email = email
        user.username = email
        print(user.email)
        if request.user.role == User.COLLECTION_AGENT or request.user.role == User.CUSTOMER:
            user.housename = house_name
            user.place = place
            user.municipality_id = municipality_id
            if profile_image is not None:
                user.profile_image = profile_image
        user.postcode = postcode
        user.state = state
        user.country = country
        user.save()
        if request.user.role == User.COLLECTION_AGENT:
            collection_agent = CollectionAgent.objects.get(
                user_id=request.user.id)
            collection_agent.aadhaar_number = aadhaar_number
            collection_agent.license_number = license_number
            if aadhaar_image is not None:
                collection_agent.aadhaar_image = aadhaar_image
            if license_image is not None:
                collection_agent.license_image = license_image
            collection_agent.save()
        return redirect('profile')


@login_required
@csrf_exempt

def change_password(request):
    if not (request.user.role == User.CUSTOMER or request.user.role == User.COLLECTION_AGENT or request.user.role == User.MUNICIPALITY):
        return HttpResponse('Unauthorized', status=401)
    if request.method == 'POST':
        current = request.POST['currentpoassword']
        new = request.POST['newpassword']
        confirm = request.POST['confirmpassword']
        user = User.objects.get(id=request.user.id)
        if new != confirm:
            messages.info(request, 'password not matching')
        elif not user.check_password(current):
            messages.info(request, 'wrong current password')
        else:
            user.set_password(new)
            user.save()
        return redirect('profile')


@login_required
def list_customer(request):
    if not (request.user.role == User.MUNICIPALITY):
        return HttpResponse('Unauthorized', status=401)
    if request.method == 'GET':
        users = User.objects.filter(
            role=User.CUSTOMER, municipality_id=request.user.id)
        context = {'title': 'Customers', 'add_button_name': 'ADD CUSTOMER',
                   'add_button_url_name': 'add_customer', 'users': users, 'is_customer_page': True}
        return render(request, 'list_customer_agent_recycler.html', context)


@login_required
@csrf_exempt

def add_customer(request):
    if not (request.user.role == User.MUNICIPALITY):
        return HttpResponse('Unauthorized', status=401)
    if request.method == 'GET':
        context = {'title': 'Add Customer', 'is_customer_page': True}
        return render(request, 'add_customer_agent_recycler.html', context)
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        phone = request.POST['phone']
        email = request.POST['email']
        house_name = request.POST['house_name']
        place = request.POST['place']
        postcode = request.POST['postcode']
        state = request.POST['state']
        country = request.POST['country']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        profile_image = request.FILES['profile_image']
        if not password1 == password2:
            messages.info(request, 'password incorrect')
        elif User.objects.filter(email=email).exists():
            messages.info(request, 'email taken')
        elif User.objects.filter(phone=phone).exists():
            messages.info(request, 'phone number already registered')
        else:
            user = User.objects.create_user(first_name=first_name, last_name=last_name, username=email,
                                            email=email, phone=phone, housename=house_name, place=place,
                                            postcode=postcode, state=state,
                                            country=country, municipality_id=request.user.id, password=password1, profile_image=profile_image,
                                            role=User.CUSTOMER, is_active=False)
            SmartBin.objects.create(user_id=user.id)
            Wallet.objects.create(amount=0, user_id=user.id)
            return redirect('list_customer')
        return redirect('add_customer')

@login_required
@csrf_exempt

def remove_customer(request, user_id):
    if not (request.user.role == User.MUNICIPALITY):
        return HttpResponse('Unauthorized', status=401)
    if request.method == 'POST':
        user = User.objects.get(id=user_id)
        user.delete()
        return redirect('list_customer')


@login_required
@csrf_exempt

def change_status_customer(request, user_id):
    if not (request.user.role == User.MUNICIPALITY):
        return HttpResponse('Unauthorized', status=401)
    if request.method == 'POST':
        user = User.objects.get(id=user_id)
        user.is_active = not user.is_active
        user.save()
        return redirect('list_customer')


@login_required
@csrf_exempt

def list_agent(request):
    if not (request.user.role == User.MUNICIPALITY):
        return HttpResponse('Unauthorized', status=401)
    if request.method == 'GET':
        users = User.objects.filter(
            role=User.COLLECTION_AGENT, municipality_id=request.user.id)
        user_ids = []
        for user in users:
            user_ids.append(user.id)
        agents = CollectionAgent.objects.filter(user_id__in=user_ids)
        context = {'title': 'Collection Agents', 'add_button_name': 'ADD COLLECTION AGENT',
                   'add_button_url_name': 'add_agent', 'users': users, 'agents': agents, 'is_agent_page': True}
        return render(request, 'list_customer_agent_recycler.html', context)


@login_required
@csrf_exempt

def add_agent(request):
    if not (request.user.role == User.MUNICIPALITY):
        return HttpResponse('Unauthorized', status=401)
    if request.method == 'GET':
        context = {'title': 'Add Agent', 'is_agent_page': True}
        return render(request, 'add_customer_agent_recycler.html', context)
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        phone = request.POST['phone']
        email = request.POST['email']
        house_name = request.POST['house_name']
        place = request.POST['place']
        postcode = request.POST['postcode']
        state = request.POST['state']
        country = request.POST['country']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        aadhaar_number = request.POST['aadhaar']
        license_number = request.POST['license']
        aadhaar_image = request.FILES['aadhaar_pic']
        license_image = request.FILES['license_pic']
        profile_image = request.FILES['profile_image']
        if not password1 == password2:
            messages.info(request, 'password incorrect')

accounts/templates/add_customer_agent_recycler.html
{% extends 'base.html'%}
{% block content %}
<div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
    {%for message in messages%}
    <div class="alert alert-danger">
            <span> {{message}}</span>
    </div>
    {%endfor%}
    <form method="post" enctype="multipart/form-data">
            {%csrf_token%}
            {% if is_agent_page == True or is_customer_page == True %}
            <div class="row mt-2">
                    <div class="col-md-6 form-group"><label class="labels">First Name</label><input
                                    type="text" class="form-control" placeholder="enter First name"
                                    name="first_name" required></div>
                    <div class="col-md-6 form-group"><label class="labels">Last name</label><input
                                    type="text" class="form-control" value="" placeholder=" enter Last name"
                                    name="last_name" required></div>
            </div>
            {%endif%}
            {% if is_recycler_page == True %}
            <div class="col-md-12 mt-3">
                <label class="labels">Name</label>
                <input type="text" class="form-control" placeholder="Enter Name"
                        name="name" required>
           </div>
            {%endif%}
            <div class="row ">
                    <div class="col-md-6 mt-3">
                            <label class="labels">Phone Number</label>
                            <input type="text" class="form-control" placeholder="Enter phone number"
                                    name="phone" required>
                    </div>
                    <div class="col-md-6 mt-3">
                            <label class="labels">Email ID</label>
                            <input type="text" class="form-control" placeholder="Enter email id"
                                    name="email" required>
                    </div>
                    {% if is_agent_page == True %}
                    <div class="col-md-6 mt-3">
                            <label class="labels">Aadhaar Number</label>
                            <input type="text" class="form-control" placeholder="Enter aadhaar number"
                                    name="aadhaar" required>
                    </div>
                    <div class="col-md-6 mt-3">
                            <label class="labels">Upload Aadhar card</label>
                            <input type="file" class="form-control" accept="image/*" name="aadhaar_pic"
                                    required>
                    </div>
                    <div class="col-md-6 mt-3">
                            <label class="labels">License Number</label>
                            <input type="text" class="form-control" placeholder="Enter License number"
                                    name="license" required>
                    </div>
                    <div class="col-md-6 mt-3">
                            <label class="labels">Upload License</label>
                            <input type="file" class="form-control" accept="image/*" name="license_pic"
                                    required>
                    </div>
                    {%endif%}
                    {% if is_recycler_page == True %}
                    <div class="col-md-12 mt-3">
                        <label class="labels">Building Name</label>
                        <input type="text" class="form-control" placeholder="Enter building name"
                                name="building_name" required>
                    </div>
                   {%endif%}
                   {% if is_agent_page == True or is_customer_page == True %}
                    <div class="col-md-12 mt-3">
                            <label class="labels">House Name</label>
                            <input class="form-control" placeholder="Enter house name " name="house_name"
                                    required>
                    </div>
                    {%endif%}
                    <div class="col-md-4 mt-3">
                            <label class="labels">Place</label>
                            <input type="text" class="form-control" placeholder="Enter your area"
                                    name="place" required>
                    </div>
                    
                    <div class="col-md-4 mt-3">
                            <label class="labels">Postcode</label>
                            <input type="text" class="form-control" placeholder="Enter postcode" required
                                    name="postcode">
                    </div>
                    <div class="col-md-6 mt-3">
                            <label class="labels">State</label>
                            <input type="text" class="form-control" value="" placeholder="State"
                                    name="state">
                    </div>
                    <div class="col-md-6 mt-3">
                            <label class="labels">Country</label>
                            <input type="text" class="form-control" placeholder="Country" name="country">
                    </div>
                    <div class="col-md-6 mt-3">
                            <label class="labels">Password</label>
                            <input type="password" class="form-control" placeholder="Enter password"
                                    name="password1">
                    </div>
                    <div class="col-md-6 mt-3">
                            <label class="labels">Confirm Password</label>
                            <input type="password" class="form-control" placeholder="Re-enter your password"
                                    name="password2">
                    </div>
                    {% if is_agent_page == True or is_customer_page == True %}
                    <div class="col-md-6 mt-3">
                            <label class="labels">Upload Profile image</label>
                            <input type="file" class="form-control" accept="image/*" name="profile_image"
                                    required>
                    </div>
                    {%endif%}
            </div>
            <div class="mt-5 text-center">
                    <button class="btn btn-primary profile-button" type="submit">ADD</button>
            </div>
    </form>
</div>
{%endblock%}

accounts/templates/add_municipality.html
{% extends 'base.html'%}
{% block content %}
<div class="row">
    <form method="post" enctype="multipart/form-data" >
        {%csrf_token%}
        <div class="row mt-12">
            <div class="col-md-12 form-group"><label class="labels">Name</label><input type="text"
                class="form-control" placeholder="enter name" name="first_name" required>
            </div>
        </div>
        <div class="row ">
            <div class="col-md-6 mt-3">
                <label class="labels">Phone Number</label>
                <input type="text" class="form-control" placeholder="Enter phone number" name="phone" required>
            </div>
            <div class="col-md-6 mt-3">
                <label class="labels">Email ID</label>
                <input type="text" class="form-control" placeholder="Enter email id" name="email" required >
            </div>
        </div>
        <div class="row ">
            <div class="col-md-4 mt-3">
                <label class="labels">Postcode</label>
                <input type="text" class="form-control" placeholder="Enter postcode" required name="postcode">
            </div>
            <div class="col-md-4 mt-3">
                <label class="labels">State</label>
                <input type="text" class="form-control" placeholder="State" name="state">
            </div>
            <div class="col-md-4 mt-3">
                <label class="labels">Country</label>
                <input type="text" class="form-control" placeholder="Country" name="country">
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mt-3">
                <label class="labels">Password</label>
                <input type="password" class="form-control" placeholder="Enter password"
                        name="password1">
            </div>
            <div class="col-md-6 mt-3">
                <label class="labels">Confirm Password</label>
                <input type="password" class="form-control" placeholder="Re-enter your password"
                        name="password2">
            </div>
        </div>
        <div class="mt-5 text-center">
            <button class="btn btn-primary profile-button" type="submit">ADD</button>
        </div>
    </form>
</div>
{%endblock%}

accounts/templates/list_municipalities.html
{% extends 'base.html'%}
{% block content %}
<div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped" id="list_customer">
                        <thead>
                            <tr>
                                <th> Name </th>
                                <th> Phone Number </th>
                                <th> Email </th>
                                <th> Status</th>
                                <th>Post Code </th>
                                <th>State</th>
                                <th>Country</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {%for user in users%}
                            <tr>
                                <td> {{user.first_name}} </td>
                                <td> {{user.phone}}</td>
                                <td> {{user.email}} </td>
                                <td>
                                    {% if user.is_active == True %}
                                     <span class="badge badge-success">Approved</span>
                                    {%else%}
                                     <span class="badge badge-danger">Disapproved</span>
                                    {%endif%}
                                </td>
                                <td> {{user.postcode}}</td>
                                <td>{{user.state}} </td>
                                <td>{{user.country}}</td>

                                <td>                         
                                    <form method="post" action="{% url 'change_status_municipalities' user.id %}">
                                        {%csrf_token%}<button class="btn btn-warning btn-sm" type="submit">APPROVE/DISAPPROVE</form>
                                </td>
                                <td>                         
                                    <form method="post" action="{% url 'remove_municipalities' user.id %}">
                                        {%csrf_token%}<button class="btn btn-danger btn-sm" type="submit">Remove</form>
                                </td>
                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

accounts/templates/map.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div id="hero">
        <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
                <form method="post" >
                        {%csrf_token%}
                        <div class="row mt-2">
                                <div class="col-md-4 form-group"><label class="labels">Location Name</label><input
                                type="text" class="form-control" name="name" id="name" required></div>
                                <div class="col-md-4 form-group"><label class="labels">Latitude</label><input
                                  type="text" class="form-control"name="latitude" id="id_latitude" required></div>
                                <div class="col-md-4 form-group"><label class="labels">Last name</label><input
                                    type="text" class="form-control" name="longitude" id="id_longitude" required></div>
                        </div>
                        <div class="mt-5 text-center">
                                <button class="btn btn-primary profile-button" type="submit">Save</button>
                        </div>
                        <div class="row mt-3">
                          <div id="map" style="width: 100%; height: 500px;"></div>
                        </div>
                </form>
        </div>
</div>
{% endblock %}

{% block script %}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCQMwCmZA5WO1ZBEXe-rKNPunXlizYhgwM"></script>
<script>
    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: -34.397, lng: 150.644},
            zoom: 8
        });
        var marker = new google.maps.Marker({
            map: map,
            draggable: true,
            animation: google.maps.Animation.DROP,
            position: {lat: -34.397, lng: 150.644}
        });
        google.maps.event.addListener(marker, 'dragend', function() {
            var latlng = marker.getPosition();
            document.getElementById('id_latitude').value = latlng.lat();
            document.getElementById('id_longitude').value = latlng.lng();
        });
    }

    window.onload = function() {
        initMap();
    }
</script>
{% endblock %}


<!-- <!DOCTYPE html>
<html>
<head>
    <title>Add Location</title>
    
</head>
<body onload="initMap()">
    <form method="post">
        {% csrf_token %}
        <label for="name">Name:</label>
        <input type="text" name="name" id="name"><br>
        <label for="latitude">Latitude:</label>
        <input type="text" name="latitude" id="id_latitude"><br>
        <label for="longitude">Longitude:</label>
        <input type="text" name="longitude" id="id_longitude"><br>
        <div id="map" style="width: 500px; height: 400px;"></div>
        <br>
        <input type="submit" value="Save">
    </form>
</body>
</html>
 -->